load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
# proto_library, cc_proto_library, and java_proto_library rules implicitly
# depend on @com_google_protobuf for protoc and proto runtimes.
# This statement defines the @com_google_protobuf repo.
http_archive(
name = "com_google_protobuf",
strip_prefix = "protobuf-3.6.1.3",
urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz"],
)

http_archive(
name = "com_google_protobuf_javalite",
strip_prefix = "protobuf-javalite",
urls = ["https://github.com/google/protobuf/archive/javalite.zip"],
)
http_archive(
    name = "google_bazel_common",
    strip_prefix = "bazel-common-0a14592ccc7d6018643d841ee61a29ae3e9d4684",
    urls = ["https://github.com/google/bazel-common/archive/0a14592ccc7d6018643d841ee61a29ae3e9d4684.zip"],
)

load("@google_bazel_common//:workspace_defs.bzl", "google_common_workspace_rules")

google_common_workspace_rules()
