load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "google_bazel_common",
    strip_prefix = "bazel-common-0a14592ccc7d6018643d841ee61a29ae3e9d4684",
    urls = ["https://github.com/google/bazel-common/archive/0a14592ccc7d6018643d841ee61a29ae3e9d4684.zip"],
)

load("@google_bazel_common//:workspace_defs.bzl", "google_common_workspace_rules")

google_common_workspace_rules()
